module.exports = {
    all: require('./all'),
    any: require('./any'),
    append: require('./append'),
    copy: require('./copy'),
    filter: require('./filter'),
    find: require('./find'),
    groupBy: require('./groupBy'),
    indexesOf: require('./indexesOf'),
    indexOf: require('./indexOf'),
    keyBy: require('./keyBy'),
    map: require('./map'),
    max: require('./max'),
    min: require('./min'),
    nth: require('./nth'),
    permute: require('./permute'),
    reduce: require('./reduce'),
    reverse: require('./reverse'),
    slice: require('./slice'),
    sort: require('./sort'),
    take: require('./take')
};
