module.exports = {
    all: require('./all'),
    any: require('./any'),
    append: require('./append'),
    filter: require('./filter'),
    find: require('./find'),
    first: require('./first'),
    fromArray: require('./fromArray'),
    gen: require('./gen'),
    indexesOf: require('./indexesOf'),
    indexOf: require('./indexOf'),
    last: require('./last'),
    map: require('./map'),
    max: require('./max'),
    min: require('./min'),
    nth: require('./nth'),
    permute: require('./permute'),
    prepend: require('./prepend'),
    range: require('./range'),
    reduce: require('./reduce'),
    reject: require('./reject'),
    repeat: require('./repeat'),
    slice: require('./slice'),
    take: require('./take'),
    takeWhile: require('./takeWhile'),
    toArray: require('./toArray')
};
